### PR TITLE
Don't report an error after successfully removing a firewall rule

### LINKED ISSUE #77: `opteadm` prints error after successful deletion of firewall rule
After creating a firewall rule, trying to delete it again seems to work, except that it prints an error to the terminal.

Starting with the default rules (ignore the flows for this issue, I think)

```
﻿bnaecker@feldspar : ~/testbed/opte-ddm-x2/cargo-bay $ pfexec ./opteadm dump-layer firewall -p opte1
Layer firewall
======================================================================
Inbound Flows
----------------------------------------------------------------------
PROTO  SRC IP           SPORT  DST IP           DPORT  HITS     ACTION
ICMP   1.1.1.1          0      172.30.0.6       0      0        fw

Outbound Flows
----------------------------------------------------------------------
PROTO  SRC IP           SPORT  DST IP           DPORT  HITS     ACTION
ICMP   172.30.0.6       0      1.1.1.1          0      212      fw

Inbound Rules
----------------------------------------------------------------------
ID       PRI    PREDICATES                                       ACTION
1        1      inner.ether.ether_type=0x806                     "STATIC: Identity"
4        65534  inner.ip.proto=TCP inner.ulp.dst=3389            "STATEFUL: Firewall"
3        65534  inner.ip.proto=ICMP                              "STATEFUL: Firewall"
2        65534  inner.ip.proto=TCP inner.ulp.dst=22              "STATEFUL: Firewall"
0        65535                                                   "DENY"

Outbound Rules
----------------------------------------------------------------------
ID       PRI    PREDICATES                                       ACTION
0        65535                                                   "STATEFUL: Firewall"

```

We can add a rule like so, and it seems to be reflected in the firewall layer:

```
bnaecker@feldspar : ~/testbed/opte-ddm-x2/cargo-bay $ pfexec ./opteadm add-fw-rule -p opte1 --action allow --dir out --hosts any --protocol any --ports any --priority 10
bnaecker@feldspar : ~/testbed/opte-ddm-x2/cargo-bay $ pfexec ./opteadm dump-layer firewall -p opte1
Layer firewall
======================================================================
Inbound Flows
----------------------------------------------------------------------
PROTO  SRC IP           SPORT  DST IP           DPORT  HITS     ACTION
ICMP   1.1.1.1          0      172.30.0.6       0      0        fw

Outbound Flows
----------------------------------------------------------------------
PROTO  SRC IP           SPORT  DST IP           DPORT  HITS     ACTION
ICMP   172.30.0.6       0      1.1.1.1          0      212      fw

Inbound Rules
----------------------------------------------------------------------
ID       PRI    PREDICATES                                       ACTION
1        1      inner.ether.ether_type=0x806                     "STATIC: Identity"
4        65534  inner.ip.proto=TCP inner.ulp.dst=3389            "STATEFUL: Firewall"
3        65534  inner.ip.proto=ICMP                              "STATEFUL: Firewall"
2        65534  inner.ip.proto=TCP inner.ulp.dst=22              "STATEFUL: Firewall"
0        65535                                                   "DENY"

Outbound Rules
----------------------------------------------------------------------
ID       PRI    PREDICATES                                       ACTION
4        10                                                      "STATEFUL: Firewall"
0        65535                                                   "STATEFUL: Firewall"

```

Then deleting it prints an error, but seems to work:

```
bnaecker@feldspar : ~/testbed/opte-ddm-x2/cargo-bay $ pfexec ./opteadm rm-fw-rule -p opte1 --dir out 4
ERROR: command RemFwRule failed: LayerNotFound("firewall")
bnaecker@feldspar : ~/testbed/opte-ddm-x2/cargo-bay $ pfexec ./opteadm dump-layer firewall -p opte1
Layer firewall
======================================================================
Inbound Flows
----------------------------------------------------------------------
PROTO  SRC IP           SPORT  DST IP           DPORT  HITS     ACTION
ICMP   1.1.1.1          0      172.30.0.6       0      0        fw

Outbound Flows
----------------------------------------------------------------------
PROTO  SRC IP           SPORT  DST IP           DPORT  HITS     ACTION
ICMP   172.30.0.6       0      1.1.1.1          0      212      fw

Inbound Rules
----------------------------------------------------------------------
ID       PRI    PREDICATES                                       ACTION
1        1      inner.ether.ether_type=0x806                     "STATIC: Identity"
4        65534  inner.ip.proto=TCP inner.ulp.dst=3389            "STATEFUL: Firewall"
3        65534  inner.ip.proto=ICMP                              "STATEFUL: Firewall"
2        65534  inner.ip.proto=TCP inner.ulp.dst=22              "STATEFUL: Firewall"
0        65535                                                   "DENY"

Outbound Rules
----------------------------------------------------------------------
ID       PRI    PREDICATES                                       ACTION
0        65535                                                   "STATEFUL: Firewall"
```

### PR DESCRIPTION
**Pull request by plotnick**
Should fix #77 by following the suggestion of @bnaecker, though I lack the infrastructure to test it properly. (I encountered this bug on my system, and was going to file an issue for it but found there already was one; so I thought I'd try to just fix it instead.)

### CODE REVIEW

**Comment by rzezeski** [comment]
This looks good. Thanks for the fix.

> though I lack the infrastructure to test it properly.

I'm a little lost, if you ran into this issue yourself presumably you have a method for testing it?

**Comment by plotnick** [comment]
> I'm a little lost, if you ran into this issue yourself presumably you have a method for testing it?

I hit the issue running `opteadm` to add & delete firewall rules. But I'm not currently set up to do full Helios builds (though I would like to be soon), and my understanding from `README.adoc` is that's the only way to actually test changes to the engine. Eyeballing the code, @bnaecker's suggestion in the issue looked like the correct logical fix, but past compiling the engine with `cargo build`, I haven't been able to verify on my own that it does actually suppress the reported "error".

**Comment by plotnick** [comment]
Update: thanks to some help from @rzezeski, I was able to recompile `xde` and actually test this change. It seems to work perfectly:
```
helios:~/omicron$ pfexec opteadm add-fw-rule -p opte0 --priority 1 --action deny --dir out --hosts ip=1.1.1.1 --protocol icmp --ports any
helios:~/omicron$ pfexec opteadm dump-layer firewall -p opte0
Layer firewall
======================================================================
Inbound Flows
----------------------------------------------------------------------
PROTO  SRC IP           SPORT  DST IP           DPORT  HITS     ACTION                

Outbound Flows
----------------------------------------------------------------------
PROTO  SRC IP           SPORT  DST IP           DPORT  HITS     ACTION                

Inbound Rules
----------------------------------------------------------------------
ID       PRI    PREDICATES                                       ACTION            

Outbound Rules
----------------------------------------------------------------------
ID       PRI    PREDICATES                                       ACTION            
0        1      inner.ip.proto=ICMP inner.ip.dst=1.1.1.1         "DENY"

helios:~/omicron$ pfexec opteadm rm-fw-rule 0 --dir out -p opte0
helios:~/omicron$ pfexec opteadm dump-layer firewall -p opte0
Layer firewall
======================================================================
Inbound Flows
----------------------------------------------------------------------
PROTO  SRC IP           SPORT  DST IP           DPORT  HITS     ACTION                

Outbound Flows
----------------------------------------------------------------------
PROTO  SRC IP           SPORT  DST IP           DPORT  HITS     ACTION                

Inbound Rules
----------------------------------------------------------------------
ID       PRI    PREDICATES                                       ACTION            

Outbound Rules
----------------------------------------------------------------------
ID       PRI    PREDICATES                                       ACTION            

```
(Notice the lack of `ERROR: command RemFwRule failed: RuleNotFound(0)` after the `opteadm rm-fw-rule` command.)

**Comment by rzezeski** [comment]
@plotnick Fantastic. Thanks for slogging through some unfamiliar territory to test it. Go ahead and merge this.

**Pull request merged**
