### PR TITLE
Remove the "external IP hack" (#236)

### PR DESCRIPTION
**Pull request by rzezeski**

### CODE REVIEW

**Comment by bnaecker** [comment]
I just wanted to check about timing here. There's a lot of integration with Dendrite needed before we can really provision instances that don't use the hack. Is the plan to keep this up and in-waiting until we do that? That's fine by me, just checking.

**Comment by rzezeski** [comment]
@bnaecker I just wanted to make sure I had a PR floated before I take leave. Though, to be fair, it could always be merged and you just have to just stay on the previous commit until you are ready to transition Omicron to the new world order (speaking of which, I believe we are already several PRs behind in Omicron that would update opte).

Anyways, I'll leave it to you when this should land.

**Comment by bnaecker** [comment]
Oh duh, I forgot we pin a commit in Omicron. Thanks!

**Comment by luqmana** [comment]
Ideally I'd want to get the no-more-vnic landed first and be able to pin omicron at a version with that. That's just currently blocked on landing the upstream viona changes.

**Comment by luqmana** [comment]
With SoftNPU having landed a couple of weeks ago, omicron has since transitioned from requiring the external IP hack. It's finally time to get rid of it altogether!

**Pull request merged**
